// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmXZtYtR9RXR-igFtrfsv2McVtmCC9wIo',
    appId: '1:234947154935:web:d118d59e137376685a94f2',
    messagingSenderId: '234947154935',
    projectId: 'aiko-ben-expense-app',
    authDomain: 'aiko-ben-expense-app.firebaseapp.com',
    storageBucket: 'aiko-ben-expense-app.appspot.com',
    measurementId: 'G-E7QSPNQQ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmm3TeKKiQDt3HEKT2OYRlYzTnNwoRYzA',
    appId: '1:234947154935:android:8584063dc1edce5b5a94f2',
    messagingSenderId: '234947154935',
    projectId: 'aiko-ben-expense-app',
    storageBucket: 'aiko-ben-expense-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOlGPypDHKfZMKTSrxG88qhp0VCkUeSDc',
    appId: '1:234947154935:ios:3a7d07f33495d5835a94f2',
    messagingSenderId: '234947154935',
    projectId: 'aiko-ben-expense-app',
    storageBucket: 'aiko-ben-expense-app.appspot.com',
    iosClientId: '234947154935-rescup30q9rmjdk36tur4v8arte0kobu.apps.googleusercontent.com',
    iosBundleId: 'com.example.aikoBenExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOlGPypDHKfZMKTSrxG88qhp0VCkUeSDc',
    appId: '1:234947154935:ios:b8fa7fadb0a0c1fe5a94f2',
    messagingSenderId: '234947154935',
    projectId: 'aiko-ben-expense-app',
    storageBucket: 'aiko-ben-expense-app.appspot.com',
    iosClientId: '234947154935-74cavt9vp1lc9a92430bi9naau3l4atd.apps.googleusercontent.com',
    iosBundleId: 'com.example.aikoBenExpenseApp.RunnerTests',
  );
}
